#!/usr/bin/env python3
"""Generate identical build provenance payloads for every supported artifact."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "packages/contracts/openapi.json"
FULL_SHA = re.compile(r"^[0-9a-f]{40}$")


def git_sha() -> str:
    override = os.environ.get("TONO_CANONICAL_SHA")
    if override:
        return override
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()


def schema_revision() -> str:
    return (ROOT / "schema/revision.txt").read_text().strip()


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sha", default=None)
    args = parser.parse_args()
    sha = args.sha or git_sha()
    if not FULL_SHA.fullmatch(sha):
        parser.error("canonical SHA must be a full 40-character lowercase Git SHA")
    revision = schema_revision()
    contract_hash = sha256(CONTRACT)
    payload = {
        "canonical_sha": sha,
        "contract_sha256": contract_hash,
        "schema_revision": revision,
    }
    encoded = json.dumps(payload, indent=2, sort_keys=True) + "\n"

    for relative in (
        "build/provenance.json",
        "apps/backend/build-provenance.json",
        "apps/web/public/build-provenance.json",
        "apps/android/app/src/main/assets/build-provenance.json",
    ):
        write(ROOT / relative, encoded)

    swift = (
        "// Generated by scripts/ci/prepare_provenance.py; do not edit.\n"
        "enum BuildProvenance {\n"
        f'    static let canonicalSHA = "{sha}"\n'
        f'    static let contractSHA256 = "{contract_hash}"\n'
        f'    static let schemaRevision = "{revision}"\n'
        "}\n"
    )
    write(ROOT / "apps/ios/Shared/BuildProvenance.generated.swift", swift)
    print(encoded, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
