#!/usr/bin/env python3
"""Generate identical build provenance payloads for every supported artifact."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "packages/contracts/openapi.json"
FULL_SHA = re.compile(r"^[0-9a-fA-F]{40}$")
SHA_ENVIRONMENT_VARIABLES = (
    "TONO_CANONICAL_SHA",
    "VERCEL_GIT_COMMIT_SHA",
    "GITHUB_SHA",
)


def resolve_sha(explicit_sha: str | None = None) -> str:
    sha = explicit_sha
    if sha is None:
        sha = next(
            (os.environ[name] for name in SHA_ENVIRONMENT_VARIABLES if name in os.environ),
            None,
        )
    if sha is None:
        try:
            sha = subprocess.check_output(
                ["git", "rev-parse", "HEAD"],
                cwd=ROOT,
                stderr=subprocess.DEVNULL,
                text=True,
            ).strip()
        except (FileNotFoundError, subprocess.CalledProcessError):
            pass
    if sha is None or not FULL_SHA.fullmatch(sha):
        raise ValueError("canonical SHA must be a full 40-character hexadecimal Git SHA")
    return sha.lower()


def schema_revision() -> str:
    return (ROOT / "schema/revision.txt").read_text().strip()


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sha", default=None)
    args = parser.parse_args()
    try:
        sha = resolve_sha(args.sha)
    except ValueError as error:
        parser.error(str(error))
    revision = schema_revision()
    contract_hash = sha256(CONTRACT)
    payload = {
        "canonical_sha": sha,
        "contract_sha256": contract_hash,
        "schema_revision": revision,
    }
    encoded = json.dumps(payload, indent=2, sort_keys=True) + "\n"

    for relative in (
        "build/provenance.json",
        "apps/backend/build-provenance.json",
        "apps/web/public/build-provenance.json",
        "apps/android/app/src/main/assets/build-provenance.json",
    ):
        write(ROOT / relative, encoded)

    swift = (
        "// Generated by scripts/ci/prepare_provenance.py; do not edit.\n"
        "enum BuildProvenance {\n"
        f'    static let canonicalSHA = "{sha}"\n'
        f'    static let contractSHA256 = "{contract_hash}"\n'
        f'    static let schemaRevision = "{revision}"\n'
        "}\n"
    )
    write(ROOT / "apps/ios/Shared/BuildProvenance.generated.swift", swift)
    print(encoded, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
