#!/usr/bin/env python3
"""Generate identical build provenance payloads for every supported artifact."""
from __future__ import annotations

import argparse
import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def git_sha() -> str:
    override = os.environ.get("TONO_CANONICAL_SHA")
    if override:
        return override
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()


def schema_revision() -> str:
    return (ROOT / "schema/revision.txt").read_text().strip()


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sha", default=None)
    args = parser.parse_args()
    sha = args.sha or git_sha()
    revision = schema_revision()
    payload = {"canonical_sha": sha, "schema_revision": revision}
    encoded = json.dumps(payload, indent=2, sort_keys=True) + "\n"

    for relative in (
        "build/provenance.json",
        "apps/backend/build-provenance.json",
        "apps/web/public/build-provenance.json",
        "apps/android/app/src/main/assets/build-provenance.json",
    ):
        write(ROOT / relative, encoded)

    swift = (
        "// Generated by scripts/ci/prepare_provenance.py; do not edit.\n"
        "enum BuildProvenance {\n"
        f'    static let canonicalSHA = "{sha}"\n'
        f'    static let schemaRevision = "{revision}"\n'
        "}\n"
    )
    write(ROOT / "apps/ios/Shared/BuildProvenance.generated.swift", swift)
    print(encoded, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
